# Generated by Django 2.2.4 on 2019-08-06 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.CharField(default='onbekend', max_length=30)),
                ('searchterm', models.CharField(default='onbekend', max_length=30)),
                ('conceptFSN', models.CharField(default='onbekend', max_length=150)),
                ('execution_time', models.DecimalField(decimal_places=2, max_digits=50)),
                ('output_available', models.BooleanField(default=True)),
                ('filename', models.CharField(default='onbekend', max_length=500)),
                ('celery_task_id', models.CharField(default='onbekend', max_length=120)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
