# Generated by Django 2.2.12 on 2020-08-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
