# Generated by Django 2.2.12 on 2020-08-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_auto_20200812_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='validation.Task'),
        ),
    ]
