# Generated by Django 2.2.12 on 2020-08-21 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validation', '0006_answer_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='access',
            field=models.ManyToManyField(blank=True, default=None, related_name='validation_task_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
