# Generated by Django 2.2.6 on 2019-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tree_excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecordbuildflat',
            name='conceptFSN',
            field=models.CharField(default='onbekend', max_length=500),
        ),
    ]
