# Generated by Django 2.2.9 on 2020-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termspacecomments',
            name='concept',
            field=models.CharField(default=7400008, max_length=300),
            preserve_default=False,
        ),
    ]
