# Generated by Django 2.2.9 on 2020-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0002_termspacecomments_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='termspacecomments',
            name='fsn',
            field=models.CharField(default='Leeg', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termspacecomments',
            name='folder',
            field=models.CharField(max_length=600),
        ),
    ]
