# Generated by Django 2.2.9 on 2020-02-06 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0004_auto_20200122_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='EclQueryResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=50)),
                ('component_title', models.CharField(max_length=500)),
                ('component_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('component_extra_dict', models.TextField(blank=True, default=None, null=True)),
                ('parents', models.TextField(blank=True, default=None, null=True)),
                ('children', models.TextField(blank=True, default=None, null=True)),
                ('descendants', models.TextField(blank=True, default=None, null=True)),
                ('ancestors', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
