# Generated by Django 2.2.11 on 2020-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0005_eclqueryresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermspaceMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('token', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
