# Generated by Django 2.2.11 on 2020-03-31 11:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0006_termspacemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermspaceTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
