# Generated by Django 2.2.11 on 2020-03-31 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0008_auto_20200331_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermspaceProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
