# Generated by Django 2.2.11 on 2020-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0009_termspaceprogressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='termspaceprogressreport',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
