# Generated by Django 2.2.11 on 2020-04-02 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('termspace', '0010_termspaceprogressreport_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermspaceUserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
