# Generated by Django 2.2.9 on 2019-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=100)),
                ('dob', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('0', 'Onbekend'), ('1', 'Man'), ('2', 'Vrouw')], default=0, max_length=2)),
                ('address_street', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('address_city', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('address_country', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('bsn', models.IntegerField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
