# Generated by Django 2.2.9 on 2019-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bsn',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
