# Generated by Django 2.2.9 on 2019-12-30 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0057_auto_20191128_1359'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epd', '0003_auto_20191227_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZibProbleem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProbleemType', models.TextField(blank=True, default=None, null=True)),
                ('ProbleemBeginDatum', models.TextField(blank=True, default=None, null=True)),
                ('ProbleemEindDatum', models.TextField(blank=True, default=None, null=True)),
                ('ProbleemStatus', models.TextField(blank=True, default=None, null=True)),
                ('VerificatieStatus', models.TextField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('Decursus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epd.Decursus')),
                ('ProbleemNaam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingCodesystemComponent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epd.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
