# Generated by Django 2.2.7 on 2019-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomed_list_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snomedlistgeneratorlog',
            name='conceptFSN',
        ),
        migrations.RemoveField(
            model_name='snomedlistgeneratorlog',
            name='searchterm',
        ),
        migrations.AddField(
            model_name='snomedlistgeneratorlog',
            name='query',
            field=models.TextField(default='onbekend'),
        ),
    ]
