# Generated by Django 2.2.6 on 2019-10-16 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20191016_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCodesystemComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesystem_id', models.CharField(max_length=50)),
                ('component_id', models.CharField(max_length=50)),
                ('component_title', models.CharField(max_length=500)),
                ('component_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='mappingcodesystem',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='mappingcodesystem',
            name='component_title',
        ),
    ]
