# Generated by Django 2.2.6 on 2019-10-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20191016_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingcodesystem',
            old_name='codesystem',
            new_name='codesystem_title',
        ),
    ]
