# Generated by Django 2.2.6 on 2019-10-17 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20191016_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtask',
            name='task_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
