# Generated by Django 2.2.6 on 2019-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_mappingtask_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtask',
            name='source_codesystem',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
