# Generated by Django 2.2.6 on 2019-10-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0012_mappingcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcomments',
            name='comment_body',
            field=models.TextField(max_length=500),
        ),
    ]
