# Generated by Django 2.2.6 on 2019-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0013_auto_20191019_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingComments',
            new_name='MappingComment',
        ),
    ]
