# Generated by Django 2.2.6 on 2019-10-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_mappingcomment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcomment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
