# Generated by Django 2.2.6 on 2019-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_auto_20191019_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcomment',
            name='comment_user',
            field=models.TextField(max_length=500),
        ),
    ]
