# Generated by Django 2.2.6 on 2019-10-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0019_auto_20191019_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('status_title', models.CharField(max_length=50)),
                ('status_id', models.CharField(max_length=50)),
                ('status_description', models.CharField(max_length=50)),
                ('status_next', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mappingcomment',
            name='comment_user',
            field=models.CharField(max_length=50),
        ),
    ]
