# Generated by Django 2.2.6 on 2019-10-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0021_auto_20191021_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcodesystemcomponent',
            name='codesystem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.MappingCodesystem'),
        ),
    ]
