# Generated by Django 2.2.6 on 2019-10-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_auto_20191021_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtask',
            name='source_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.MappingCodesystemComponent'),
        ),
    ]
