# Generated by Django 2.2.6 on 2019-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0029_auto_20191022_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingrule',
            name='mapadvice',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='mapcorrelation',
            field=models.CharField(blank=True, choices=[('447559001', 'Broad to narrow'), ('447557004', 'Exact match'), ('447558009', 'Narrow to broad'), ('447560006', 'Partial overlap'), ('447556008', 'Not mappable'), ('447561005', 'Not specified')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='mapgroup',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='mappriority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='maprule',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
