# Generated by Django 2.2.6 on 2019-10-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0030_auto_20191022_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='use_mapadvice',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingproject',
            name='use_mapcorrelation',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingproject',
            name='use_mapgroup',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingproject',
            name='use_mappriority',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingproject',
            name='use_maprule',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
