# Generated by Django 2.2.6 on 2019-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0035_mappingproject_source_codesystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingproject',
            name='source_codesystem',
        ),
    ]
