# Generated by Django 2.2.6 on 2019-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0036_remove_mappingproject_source_codesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
