# Generated by Django 2.2.6 on 2019-10-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0041_mappingprogressrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingprogressrecord',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingProject'),
            preserve_default=False,
        ),
    ]
