# Generated by Django 2.2.6 on 2019-10-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0044_auto_20191030_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingcorrelation',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
