# Generated by Django 2.2.6 on 2019-10-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0045_mappingcorrelation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingcorrelation',
            name='project_id',
        ),
    ]
