# Generated by Django 2.2.6 on 2019-10-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0046_remove_mappingcorrelation_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingrule',
            name='mapcorrelation_type',
        ),
        migrations.DeleteModel(
            name='MappingCorrelation',
        ),
    ]
