# Generated by Django 2.2.7 on 2019-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0048_mappingtaskaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtaskaudit',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
