# Generated by Django 2.2.7 on 2019-11-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0050_mappingproject_project_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingproject',
            old_name='project_types',
            new_name='project_type',
        ),
    ]
