# Generated by Django 2.2.7 on 2019-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0054_mappingcodesystem_codesystem_extra_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingcodesystem',
            name='codesystem_extra_dict',
        ),
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='codesystem_extra_dict',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
