# Generated by Django 2.2.9 on 2020-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0057_auto_20191128_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingcodesystemcomponent',
            name='component_extra_1',
        ),
        migrations.RemoveField(
            model_name='mappingcodesystemcomponent',
            name='component_extra_2',
        ),
        migrations.RemoveField(
            model_name='mappingcodesystemcomponent',
            name='component_extra_3',
        ),
        migrations.RemoveField(
            model_name='mappingcodesystemcomponent',
            name='component_extra_4',
        ),
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='ancestors',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='children',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='descendants',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='parents',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
