# Generated by Django 2.2.9 on 2020-03-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0062_auto_20200302_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingReleaseCandidateRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_status', models.TextField(blank=True, default=None, null=True)),
                ('task_user', models.TextField(blank=True, default=None, null=True)),
                ('static_source_component', models.TextField(blank=True, default=None, null=True)),
                ('static_target_component', models.TextField(blank=True, default=None, null=True)),
                ('mapgroup', models.IntegerField(blank=True, default=None, null=True)),
                ('mappriority', models.IntegerField(blank=True, default=None, null=True)),
                ('mapcorrelation', models.CharField(blank=True, choices=[('447559001', 'Broad to narrow'), ('447557004', 'Exact match'), ('447558009', 'Narrow to broad'), ('447560006', 'Partial overlap'), ('447556008', 'Not mappable'), ('447561005', 'Not specified')], default=None, max_length=50, null=True)),
                ('mapadvice', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('maprule', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mapspecifies', models.TextField(blank=True, default=None, null=True)),
                ('export_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingRule')),
                ('export_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingTask')),
                ('export_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_component', to='mapping.MappingCodesystemComponent')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_component', to='mapping.MappingCodesystemComponent')),
            ],
        ),
        migrations.CreateModel(
            name='MappingReleaseCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('rules', models.ManyToManyField(to='mapping.MappingReleaseCandidateRules')),
            ],
        ),
    ]
