# Generated by Django 2.2.9 on 2020-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0063_mappingreleasecandidate_mappingreleasecandidaterules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='export_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
