# Generated by Django 2.2.9 on 2020-03-02 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0064_auto_20200302_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='export_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
