# Generated by Django 2.2.9 on 2020-03-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0069_auto_20200302_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingreleasecandidate',
            name='rules',
        ),
        migrations.AddField(
            model_name='mappingreleasecandidaterules',
            name='export_rc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingReleaseCandidate'),
        ),
    ]
