# Generated by Django 2.2.9 on 2020-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0077_mappingreleasecandidate_codesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_contact',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_copyright',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_experimental',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_publisher',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_sourceCanonical',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='metadata_version',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
