# Generated by Django 2.2.9 on 2020-03-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0078_auto_20200307_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingcodesystem',
            name='component_fhir_uri',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mappingcodesystem',
            name='codesystem_fhir_uri',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
