# Generated by Django 2.2.9 on 2020-03-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0080_auto_20200307_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingreleasecandidate',
            old_name='source_codesystem',
            new_name='codesystem',
        ),
        migrations.RemoveField(
            model_name='mappingreleasecandidate',
            name='target_codesystem',
        ),
    ]
