# Generated by Django 2.2.9 on 2020-03-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0081_auto_20200307_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='source_codesystem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_source', to='mapping.MappingCodesystem'),
        ),
        migrations.AddField(
            model_name='mappingproject',
            name='target_codesystem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_target', to='mapping.MappingCodesystem'),
        ),
    ]
