# Generated by Django 2.2.9 on 2020-03-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0084_auto_20200316_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingreleasecandidatefhirconceptmap',
            old_name='finished',
            new_name='deprecated',
        ),
    ]
