# Generated by Django 2.2.11 on 2020-03-20 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0086_mappingreleasecandidatefhirconceptmap_rc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcodesystemcomponent',
            name='component_extra_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
