# Generated by Django 2.2.11 on 2020-03-20 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0087_auto_20200320_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingcodesystemcomponent',
            name='component_terms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
