# Generated by Django 2.2.11 on 2020-03-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0088_mappingcodesystemcomponent_component_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingcodesystemcomponent',
            old_name='component_terms',
            new_name='descriptions',
        ),
    ]
