# Generated by Django 2.2.11 on 2020-03-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0089_auto_20200320_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='source_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_component', to='mapping.MappingCodesystemComponent'),
        ),
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='target_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_component', to='mapping.MappingCodesystemComponent'),
        ),
    ]
