# Generated by Django 2.2.11 on 2020-03-24 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0091_auto_20200324_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcomment',
            name='comment_body',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='mapspecifies',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='static_source_component',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mappingreleasecandidaterules',
            name='static_target_component',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
