# Generated by Django 2.2.11 on 2020-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0092_auto_20200324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingcomment',
            name='comment_title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
