# Generated by Django 2.2.11 on 2020-04-17 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0094_auto_20200416_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='access',
            field=models.ManyToManyField(blank=True, default=None, related_name='access_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
