# Generated by Django 2.2.12 on 2020-04-23 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0095_mappingproject_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='access',
            field=models.ManyToManyField(blank=True, default=None, related_name='access_rc_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
