# Generated by Django 2.2.13 on 2020-06-22 14:52

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0098_auto_20200622_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingeclpart',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
