# Generated by Django 2.2.13 on 2020-06-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0102_mappingtaskaudit_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingeclpart',
            name='export_finished',
            field=models.BooleanField(default=True),
        ),
    ]
