# Generated by Django 2.2.13 on 2020-09-18 11:27

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0103_mappingeclpart_export_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingEclPartExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.MappingTask')),
            ],
        ),
    ]
