# Generated by Django 2.2.16 on 2020-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0104_mappingeclpartexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtask',
            name='category',
            field=models.CharField(default='Prioriteit 1', max_length=500),
            preserve_default=False,
        ),
    ]
