# Generated by Django 2.2.16 on 2020-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0105_mappingtask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='export_all',
            field=models.BooleanField(default=False),
        ),
    ]
