# Generated by Django 2.2.16 on 2020-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0106_mappingreleasecandidate_export_all'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mappingcodesystemcomponent',
            index=models.Index(fields=['codesystem_id'], name='mapping_map_codesys_2e9a2e_idx'),
        ),
    ]
