# Generated by Django 2.2.16 on 2020-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0108_auto_20200929_1014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mappingcodesystem',
            constraint=models.UniqueConstraint(fields=('id',), name='Unique ID'),
        ),
    ]
