# Generated by Django 2.2.16 on 2020-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0110_auto_20201029_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingreleasecandidate',
            name='export_project',
            field=models.ManyToManyField(blank=True, default=[], related_name='project', to='mapping.MappingProject'),
        ),
    ]
