# Generated by Django 2.2.16 on 2020-11-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0111_auto_20201117_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MappingEclQuery',
        ),
    ]
