# Generated by Django 2.2.16 on 2020-12-07 11:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0112_delete_mappingeclquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingproject',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
