# Generated by Django 2.2.16 on 2020-12-16 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0113_mappingproject_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingproject',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
