# Generated by Django 2.2.16 on 2021-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0114_auto_20201216_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingreleasecandidate',
            old_name='metadata_sourceCanonical',
            new_name='metadata_sourceUri',
        ),
    ]
