# Generated by Django 3.1.7 on 2021-03-02 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0116_auto_20210227_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingreleasecandidaterules',
            name='accepted',
        ),
        migrations.AddField(
            model_name='mappingreleasecandidaterules',
            name='accepted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='mappingreleasecandidaterules',
            name='rejected',
        ),
        migrations.AddField(
            model_name='mappingreleasecandidaterules',
            name='rejected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None),
        ),
    ]
