# Generated by Django 3.1.7 on 2021-04-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0122_mappingproject_automap_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingproject',
            name='automap_valueset',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
