# Generated by Django 2.2.12 on 2020-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsn', models.CharField(max_length=300)),
                ('sctid', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='attributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsn', models.CharField(max_length=300)),
                ('sctid', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default=None)),
                ('attributes', models.ManyToManyField(to='postcoordination.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_values',
            field=models.ManyToManyField(to='postcoordination.attributeValue'),
        ),
    ]
