# Generated by Django 2.2.12 on 2020-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcoordination', '0002_auto_20200512_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, default=None, to='postcoordination.attributeValue'),
        ),
        migrations.AlterField(
            model_name='template',
            name='attributes',
            field=models.ManyToManyField(blank=True, default=None, to='postcoordination.attribute'),
        ),
    ]
