# Generated by Django 2.2.12 on 2020-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcoordination', '0005_auto_20200513_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='attributeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=None)),
                ('fsn', models.CharField(max_length=300)),
                ('sctid', models.CharField(max_length=300)),
                ('attribute_values', models.ManyToManyField(blank=True, default=None, to='postcoordination.attributeValue')),
            ],
        ),
        migrations.CreateModel(
            name='rootConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsn', models.CharField(max_length=300)),
                ('sctid', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='attributes',
            field=models.ManyToManyField(blank=True, default=None, related_name='AttributeSets', to='postcoordination.attributeSet'),
        ),
        migrations.AlterField(
            model_name='template',
            name='root_concept',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rootAttribute', to='postcoordination.rootConcept'),
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
        migrations.AddField(
            model_name='attributeset',
            name='template',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Template', to='postcoordination.template'),
        ),
    ]
