# Generated by Django 2.2.12 on 2020-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcoordination', '0007_auto_20200515_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeset',
            name='template',
        ),
        migrations.AddField(
            model_name='attributeset',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
